# Generated by Django 5.0.1 on 2024-11-14 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GAD7Response',
        ),
    ]
