# Generated by Django 5.0.1 on 2024-11-15 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_gad7response_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodentry',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
