# Generated by Django 5.0.1 on 2024-11-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_hotline'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
