# Generated by Django 5.0.1 on 2024-11-18 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_subcategory_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='color',
            field=models.CharField(choices=[('#ADD8E6', 'Light Blue'), ('#FFFFE0', 'Light Yellow'), ('#D3A6FF', 'Light Violet'), ('#FFB6C1', 'Light Pink')], default='#ADD8E6', max_length=7),
        ),
    ]
