# Generated by Django 5.0.1 on 2024-11-18 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_subcategory_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
