# Generated by Django 5.0.1 on 2024-11-18 01:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_task_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completion_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
