# Generated by Django 5.0.1 on 2024-11-18 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_alter_task_completion_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
