# Generated by Django 5.0.1 on 2024-11-18 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_exercisecompletion_delete_exerciseprogress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExerciseCompletion',
        ),
    ]
