# Generated by Django 5.0.1 on 2024-11-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_yogacompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='yogacompletion',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
