# Generated by Django 5.0.1 on 2024-11-18 22:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_yogacompletion_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameResult',
            new_name='Distraction',
        ),
    ]
