# Generated by Django 5.0.1 on 2024-11-19 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_timemanagementactivity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeManagementActivity',
        ),
    ]
