# Generated by Django 5.0.1 on 2024-11-19 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0027_timeslot_delete_timemanagementactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='user',
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.activity'),
        ),
    ]
