# Generated by Django 5.0.1 on 2024-11-19 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0028_activity_remove_timeslot_user_alter_timeslot_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
