# Generated by Django 5.0.1 on 2024-11-19 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0030_timeslotschedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='TimeSlotSchedule',
        ),
    ]
