# Generated by Django 4.2.7 on 2024-11-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0033_distraction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distraction',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='distraction',
            name='score',
            field=models.IntegerField(),
        ),
    ]
