# Generated by Django 5.0.1 on 2024-11-23 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0039_remove_task_deleted_remove_task_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
