# Generated by Django 5.0.1 on 2024-11-23 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0041_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
