# Generated by Django 5.0.1 on 2024-11-23 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0044_task_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
