# Generated by Django 5.0.1 on 2024-11-25 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0048_availability'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
