# Generated by Django 5.0.1 on 2024-11-25 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0050_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], max_length=20),
        ),
    ]
