# Generated by Django 5.0.1 on 2024-11-25 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0051_alter_availability_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
    ]
